// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: todos.sql

package orm

import (
	"context"
	"time"
)

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (content, priority, created_at, updated_at)
VALUES (?, ?, ?, ?)
RETURNING id, content, priority, completed, created_at, updated_at
`

type CreateTodoParams struct {
	Content   string    `json:"content"`
	Priority  string    `json:"priority"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, createTodo,
		arg.Content,
		arg.Priority,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.Priority,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTodo = `-- name: DeleteTodo :exec
DELETE FROM todos WHERE id = ?
`

func (q *Queries) DeleteTodo(ctx context.Context, id int) error {
	_, err := q.db.ExecContext(ctx, deleteTodo, id)
	return err
}

const getActiveTodos = `-- name: GetActiveTodos :many
SELECT id, content, priority, completed, created_at, updated_at 
FROM todos 
WHERE completed = FALSE 
ORDER BY created_at DESC
`

func (q *Queries) GetActiveTodos(ctx context.Context) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, getActiveTodos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Todo{}
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.Priority,
			&i.Completed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllTodos = `-- name: GetAllTodos :many
SELECT id, content, priority, completed, created_at, updated_at 
FROM todos 
ORDER BY created_at DESC
`

func (q *Queries) GetAllTodos(ctx context.Context) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, getAllTodos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Todo{}
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.Priority,
			&i.Completed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCompletedTodos = `-- name: GetCompletedTodos :many
SELECT id, content, priority, completed, created_at, updated_at 
FROM todos 
WHERE completed = TRUE 
ORDER BY updated_at DESC
`

func (q *Queries) GetCompletedTodos(ctx context.Context) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, getCompletedTodos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Todo{}
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.Priority,
			&i.Completed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTodoByID = `-- name: GetTodoByID :one
SELECT id, content, priority, completed, created_at, updated_at 
FROM todos 
WHERE id = ?
`

func (q *Queries) GetTodoByID(ctx context.Context, id int) (Todo, error) {
	row := q.db.QueryRowContext(ctx, getTodoByID, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.Priority,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const toggleTodoCompleted = `-- name: ToggleTodoCompleted :exec
UPDATE todos 
SET completed = NOT completed, updated_at = ? 
WHERE id = ?
`

type ToggleTodoCompletedParams struct {
	UpdatedAt time.Time `json:"updated_at"`
	ID        int       `json:"id"`
}

func (q *Queries) ToggleTodoCompleted(ctx context.Context, arg ToggleTodoCompletedParams) error {
	_, err := q.db.ExecContext(ctx, toggleTodoCompleted, arg.UpdatedAt, arg.ID)
	return err
}

const updateTodoContent = `-- name: UpdateTodoContent :exec
UPDATE todos 
SET content = ?, updated_at = ? 
WHERE id = ?
`

type UpdateTodoContentParams struct {
	Content   string    `json:"content"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        int       `json:"id"`
}

func (q *Queries) UpdateTodoContent(ctx context.Context, arg UpdateTodoContentParams) error {
	_, err := q.db.ExecContext(ctx, updateTodoContent, arg.Content, arg.UpdatedAt, arg.ID)
	return err
}

const updateTodoPriority = `-- name: UpdateTodoPriority :exec
UPDATE todos 
SET priority = ?, updated_at = ? 
WHERE id = ?
`

type UpdateTodoPriorityParams struct {
	Priority  string    `json:"priority"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        int       `json:"id"`
}

func (q *Queries) UpdateTodoPriority(ctx context.Context, arg UpdateTodoPriorityParams) error {
	_, err := q.db.ExecContext(ctx, updateTodoPriority, arg.Priority, arg.UpdatedAt, arg.ID)
	return err
}
